/* The following code was generated by JFlex 1.4.3 on 9/26/11 11:22 PM */

import java_cup.*;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/26/11 11:22 PM from the specification file
 * <tt>lua.flex</tt>
 */
class LuaLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\34\1\2\1\0\1\34\1\1\22\0\1\34\1\0\1\32"+
    "\1\15\1\0\1\20\1\0\1\33\1\3\1\4\1\20\1\20\1\13"+
    "\1\20\1\14\1\20\1\25\11\22\1\11\1\12\1\16\1\17\1\16"+
    "\2\0\1\23\2\23\1\27\1\23\1\23\2\21\1\21\2\21\1\21"+
    "\1\21\1\21\1\30\1\21\1\21\1\21\1\21\1\31\3\21\1\26"+
    "\2\21\1\5\1\0\1\6\1\20\1\21\1\0\1\40\1\53\1\37"+
    "\1\52\1\24\1\41\1\21\1\51\1\45\1\21\1\54\1\35\1\21"+
    "\1\43\1\36\1\47\1\21\1\46\1\55\1\44\1\42\1\21\1\50"+
    "\1\26\2\21\1\7\1\0\1\10\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\2\15\1\16\1\17"+
    "\1\20\1\17\1\20\2\0\14\17\1\15\1\21\1\0"+
    "\2\17\1\0\1\22\1\17\1\23\11\17\1\24\1\25"+
    "\2\17\1\26\1\17\1\0\1\17\1\27\1\20\1\17"+
    "\1\30\1\31\3\17\1\32\1\33\6\17\1\20\1\34"+
    "\4\17\1\35\1\36\5\17\1\37\1\40\1\17\1\41"+
    "\2\17\1\42\1\43\1\44\1\17\1\45\1\46\1\17"+
    "\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\212\0\56\0\56"+
    "\0\270\0\56\0\346\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc"+
    "\0\u01fa\0\u0228\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c"+
    "\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422\0\56\0\u0450\0\u047e"+
    "\0\u04ac\0\u04da\0\56\0\u0508\0\346\0\u0536\0\u0564\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\346\0\346"+
    "\0\u06d4\0\u0702\0\346\0\u0730\0\u075e\0\u078c\0\346\0\u04da"+
    "\0\u07ba\0\346\0\346\0\u07e8\0\u0816\0\u0844\0\346\0\346"+
    "\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4"+
    "\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\346\0\346\0\u0a9a\0\u0ac8"+
    "\0\u0af6\0\u0b24\0\u0b52\0\346\0\346\0\u0b80\0\346\0\u0bae"+
    "\0\u0bdc\0\346\0\346\0\346\0\u0c0a\0\346\0\346\0\u0c38"+
    "\0\346";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\23\1\25\1\26\4\23\1\27"+
    "\1\30\1\4\1\31\1\32\1\23\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\23\1\42\1\23\1\43"+
    "\1\44\2\23\17\2\1\45\40\2\1\4\14\2\1\45"+
    "\52\2\1\46\2\2\1\45\36\2\17\0\1\45\36\0"+
    "\17\2\1\45\1\2\11\23\3\2\21\23\17\2\1\45"+
    "\2\2\1\24\2\2\1\24\1\2\1\47\45\2\1\45"+
    "\1\2\11\23\3\2\1\50\5\23\1\51\12\23\17\2"+
    "\1\45\2\2\1\24\2\2\1\24\1\52\1\47\45\2"+
    "\1\45\1\2\11\27\1\53\2\2\21\27\17\2\1\45"+
    "\1\2\11\30\1\2\1\53\1\2\21\30\17\2\1\45"+
    "\1\2\11\23\3\2\1\23\1\54\17\23\17\2\1\45"+
    "\1\2\11\23\3\2\11\23\1\55\7\23\17\2\1\45"+
    "\1\2\11\23\3\2\6\23\1\56\12\23\17\2\1\45"+
    "\1\2\11\23\3\2\1\23\1\57\1\23\1\60\1\23"+
    "\1\61\13\23\17\2\1\45\1\2\11\23\3\2\6\23"+
    "\1\62\12\23\17\2\1\45\1\2\11\23\3\2\1\23"+
    "\1\63\6\23\1\64\10\23\17\2\1\45\1\2\11\23"+
    "\3\2\11\23\1\65\2\23\1\66\4\23\17\2\1\45"+
    "\1\2\11\23\3\2\4\23\1\67\1\23\1\70\12\23"+
    "\17\2\1\45\1\2\3\23\1\71\5\23\3\2\21\23"+
    "\17\2\1\45\1\2\11\23\3\2\14\23\1\72\4\23"+
    "\17\2\1\45\1\2\11\23\3\2\1\23\1\73\17\23"+
    "\17\2\1\45\1\2\11\23\3\2\11\23\1\74\7\23"+
    "\56\0\17\2\1\45\10\2\1\75\44\2\1\45\1\2"+
    "\11\23\3\2\20\23\1\76\17\2\1\45\1\2\11\23"+
    "\3\2\15\23\1\77\3\23\17\2\1\45\2\2\4\100"+
    "\1\2\1\100\7\2\3\100\10\2\2\100\21\2\1\45"+
    "\1\2\11\23\3\2\2\23\1\101\16\23\17\2\1\45"+
    "\1\2\11\23\3\2\15\23\1\102\3\23\17\2\1\45"+
    "\1\2\11\23\3\2\11\23\1\103\7\23\17\2\1\45"+
    "\1\2\11\23\3\2\1\104\20\23\17\2\1\45\1\2"+
    "\11\23\3\2\6\23\1\105\12\23\17\2\1\45\1\2"+
    "\11\23\3\2\7\23\1\106\11\23\17\2\1\45\1\2"+
    "\11\23\3\2\7\23\1\107\11\23\17\2\1\45\1\2"+
    "\11\23\3\2\1\110\20\23\17\2\1\45\1\2\11\23"+
    "\3\2\5\23\1\111\13\23\17\2\1\45\1\2\3\23"+
    "\1\112\5\23\3\2\21\23\17\2\1\45\1\2\11\23"+
    "\3\2\7\23\1\113\2\23\1\114\6\23\17\2\1\45"+
    "\1\2\11\23\3\2\10\23\1\115\10\23\17\2\1\45"+
    "\1\2\3\23\1\116\5\23\3\2\21\23\17\2\1\45"+
    "\11\2\1\117\43\2\1\45\1\2\3\23\1\120\5\23"+
    "\3\2\21\23\17\2\1\45\1\2\11\23\3\2\3\23"+
    "\1\121\15\23\17\2\1\45\1\2\11\23\3\2\20\23"+
    "\1\122\17\2\1\45\1\2\11\23\3\2\2\23\1\123"+
    "\16\23\17\2\1\45\1\2\11\23\3\2\10\23\1\124"+
    "\10\23\17\2\1\45\1\2\3\23\1\125\5\23\3\2"+
    "\21\23\17\2\1\45\1\2\11\23\3\2\6\23\1\126"+
    "\12\23\17\2\1\45\1\2\11\23\3\2\5\23\1\127"+
    "\13\23\17\2\1\45\1\2\3\23\1\130\5\23\3\2"+
    "\21\23\17\2\1\45\1\2\11\23\3\2\1\131\20\23"+
    "\17\2\1\45\1\2\11\23\3\2\3\23\1\132\15\23"+
    "\17\2\1\45\2\2\1\117\2\2\1\117\47\2\1\45"+
    "\1\2\11\23\3\2\10\23\1\133\10\23\17\2\1\45"+
    "\1\2\11\23\3\2\1\134\20\23\17\2\1\45\1\2"+
    "\3\23\1\135\5\23\3\2\21\23\17\2\1\45\1\2"+
    "\11\23\3\2\7\23\1\136\11\23\17\2\1\45\1\2"+
    "\11\23\3\2\1\137\20\23\17\2\1\45\1\2\11\23"+
    "\3\2\11\23\1\140\7\23\17\2\1\45\1\2\11\23"+
    "\3\2\3\23\1\141\15\23\17\2\1\45\1\2\3\23"+
    "\1\142\5\23\3\2\21\23\17\2\1\45\1\2\11\23"+
    "\3\2\17\23\1\143\1\23\17\2\1\45\1\2\11\23"+
    "\3\2\4\23\1\144\14\23\17\2\1\45\1\2\11\23"+
    "\3\2\10\23\1\145\10\23\17\2\1\45\1\2\11\23"+
    "\3\2\6\23\1\146\12\23\17\2\1\45\1\2\11\23"+
    "\3\2\7\23\1\147\11\23\17\2\1\45\1\2\11\23"+
    "\3\2\1\23\1\150\17\23\17\2\1\45\1\2\11\23"+
    "\3\2\6\23\1\151\12\23";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3174];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\24\1\2\0\14\1\1\11\1\1\1\0\2\1"+
    "\1\0\22\1\1\0\54\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
	
	public int getLine() {
		return yyline;
	}
	
	public int getColumn() {
		return yycolumn;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LuaLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LuaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 39: 
          { return symbol(LuaSym.FUNCTION);
          }
        case 40: break;
        case 13: 
          { return symbol(LuaSym.RELOP, yytext());
          }
        case 41: break;
        case 11: 
          { return symbol(LuaSym.DOT);
          }
        case 42: break;
        case 37: 
          { return symbol(LuaSym.RETURN);
          }
        case 43: break;
        case 17: 
          { return symbol(LuaSym.CONCAT);
          }
        case 44: break;
        case 31: 
          { return symbol(LuaSym.LOCAL);
          }
        case 45: break;
        case 36: 
          { return symbol(LuaSym.ELSEIF);
          }
        case 46: break;
        case 8: 
          { return symbol(LuaSym.COLON);
          }
        case 47: break;
        case 14: 
          { return symbol(LuaSym.ARITOP, yytext());
          }
        case 48: break;
        case 29: 
          { return symbol(LuaSym.TRUE);
          }
        case 49: break;
        case 6: 
          { return symbol(LuaSym.LCURLY);
          }
        case 50: break;
        case 23: 
          { return symbol(LuaSym.END);
          }
        case 51: break;
        case 35: 
          { return symbol(LuaSym.BREAK);
          }
        case 52: break;
        case 34: 
          { return symbol(LuaSym.WHILE);
          }
        case 53: break;
        case 4: 
          { return symbol(LuaSym.LBRACK);
          }
        case 54: break;
        case 33: 
          { return symbol(LuaSym.UNTIL);
          }
        case 55: break;
        case 28: 
          { return symbol(LuaSym.ELSE);
          }
        case 56: break;
        case 26: 
          { return symbol(LuaSym.NOT);
          }
        case 57: break;
        case 24: 
          { return symbol(LuaSym.AND);
          }
        case 58: break;
        case 30: 
          { return symbol(LuaSym.THEN);
          }
        case 59: break;
        case 2: 
          { return symbol(LuaSym.LPAREN);
          }
        case 60: break;
        case 16: 
          { return symbol(LuaSym.NUMERO, yytext());
          }
        case 61: break;
        case 12: 
          { return symbol(LuaSym.POUND);
          }
        case 62: break;
        case 22: 
          { return symbol(LuaSym.DO);
          }
        case 63: break;
        case 18: 
          { return symbol(LuaSym.STRING, yytext());
          }
        case 64: break;
        case 10: 
          { return symbol(LuaSym.COMMA);
          }
        case 65: break;
        case 20: 
          { return symbol(LuaSym.IF);
          }
        case 66: break;
        case 32: 
          { return symbol(LuaSym.FALSE);
          }
        case 67: break;
        case 9: 
          { return symbol(LuaSym.SEMICOL);
          }
        case 68: break;
        case 7: 
          { return symbol(LuaSym.RCURLY);
          }
        case 69: break;
        case 19: 
          { return symbol(LuaSym.OR);
          }
        case 70: break;
        case 21: 
          { return symbol(LuaSym.IN);
          }
        case 71: break;
        case 5: 
          { return symbol(LuaSym.RBRACK);
          }
        case 72: break;
        case 38: 
          { return symbol(LuaSym.REPEAT);
          }
        case 73: break;
        case 25: 
          { return symbol(LuaSym.FOR);
          }
        case 74: break;
        case 27: 
          { return symbol(LuaSym.NIL);
          }
        case 75: break;
        case 3: 
          { return symbol(LuaSym.RPAREN);
          }
        case 76: break;
        case 15: 
          { return symbol(LuaSym.ID, yytext());
          }
        case 77: break;
        case 1: 
          { 
          }
        case 78: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
