
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 27 23:52:19 GMT-03:00 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 50;
  public static final int DIVIDE = 17;
  public static final int FUNCTION = 22;
  public static final int MULT = 16;
  public static final int GE = 45;
  public static final int CONCAT = 13;
  public static final int ATT = 14;
  public static final int LPAREN = 2;
  public static final int REPEAT = 25;
  public static final int FOR = 24;
  public static final int MINUS = 18;
  public static final int RPAREN = 3;
  public static final int NOT = 33;
  public static final int AND = 32;
  public static final int LT = 42;
  public static final int ELSEIF = 37;
  public static final int NIL = 41;
  public static final int IN = 29;
  public static final int OR = 31;
  public static final int COMMA = 10;
  public static final int SEMICOL = 9;
  public static final int UNTIL = 26;
  public static final int PLUS = 15;
  public static final int IF = 34;
  public static final int EXP = 19;
  public static final int RELOP = 51;
  public static final int ID = 48;
  public static final int DOT = 11;
  public static final int LE = 44;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int EQUAL = 47;
  public static final int TRUE = 39;
  public static final int POUND = 12;
  public static final int error = 1;
  public static final int LCURLY = 6;
  public static final int MOD = 20;
  public static final int BREAK = 30;
  public static final int RCURLY = 7;
  public static final int LBRACK = 4;
  public static final int COLON = 8;
  public static final int ELSE = 36;
  public static final int RBRACK = 5;
  public static final int WHILE = 27;
  public static final int NEQUAL = 46;
  public static final int THEN = 35;
  public static final int END = 38;
  public static final int STRING = 49;
  public static final int LOCAL = 21;
  public static final int FALSE = 40;
  public static final int GT = 43;
  public static final int DO = 28;
}

